### PR TITLE
Cleanup, switching maintainer.

### PR DESCRIPTION
**Pull request by mikepurvis**
@safrimus @ibaranov-cp @abencz  to review.

Note that the bulk of the diff is the first commit, which was automatic: `find . -name .svn | xargs git rm -r`

So for review purposes, view the remaining three individually (or I can just commit the first one to hydro-devel).

### CODE REVIEW

**Comment by safrimus** [comment]
LGTM

**Comment by abencz** [comment]
LGTM too.

**Comment by abencz** [comment]
Should test it on the robot before blooming.

**Comment by mikepurvis** [comment]
Yup, agree with bench and robot testing.

**Comment by mikepurvis** [comment]
On-robot testing complete, looks good.

**Pull request merged**
